name: Deploy

on:
  schedule:
    - cron "0 21 * * 1"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
                with:
                    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                    heroku_app_name: "our-recipes-book"
                    heroku_email: "beniusij@gmail.com"